### ISSUE TITLE
Turso DB

### ISSUE THREAD

**Issue by NJWong** [NJWong/me-api-nextjs#1]
**Tasks**
- [ ] Create new Turso project
- [ ] Drizzle ORM to create basic Species schema
- [ ] Basic read query for Species table

**Comment by NJWong** [comment]
Implementation details:
* Turso used for hosting SQlite DB
* Tables created for Species, Genders, Characters, Affiliations
* Using Drizzle ORM for schema definitions
