### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by NJWong** [NJWong/me-api-nextjs#2]
**Tasks**
- [ ] Decide which auth provider to use
- [ ] Create auth middleware
- [ ] Basic write query to Species table (protected API route)

**Comment by NJWong** [comment]
Implementation notes:
* Using Auth0 for authentication
* Configured Auth0 application to not allow new signups
* Created auth middleware for `api/protected/` routes
* Routes using `api/public` are not protected
* Added `admin/` protected route to allow signin via Auth0
